-- Creacion de las tablas Stage, Intermedias y Finales --

-- Tablas STG --

CREATE TABLE [STG_DIM_PRODUCTO](
COD_PRODUCTO Varchar(500) NOT NULL,
DESC_PRODUCTO Varchar(500) NOT NULL
)

CREATE TABLE [STG_DIM_CATEGORIA](
COD_CATEGORIA Varchar(500) NOT NULL,
DESC_CATEGORIA Varchar(500)NOT NULL
)

CREATE TABLE [STG_DIM_CLIENTE] (
COD_CLIENTE Varchar(500) NOT NULL,
DESC_CLIENTE Varchar(500) NOT NULL
)

CREATE TABLE [STG_DIM_PAIS](
COD_PAIS Varchar(500) NOT NULL,
DESC_PAIS Varchar(500) NOT NULL
)

CREATE TABLE [STG_DIM_VENDEDOR](
COD_VENDEDOR Varchar(500) NOT NULL,
DESC_VENDEDOR Varchar(500) NOT NULL
)

CREATE TABLE [STG_DIM_SUCURSAL](
COD_SUCURSAL Varchar(15) NOT NULL,
DESC_SUCURSAL Varchar(100) NOT NULL
)

CREATE TABLE [STG_FACT_VENTAS] (
COD_PRODUCTO Varchar(500) NOT NULL,
COD_CATEGORIA Varchar(500) NOT NULL,
COD_CLIENTE Varchar(500) NOT NULL,
COD_PAIS Varchar(500) NOT NULL,
COD_VENDEDOR Varchar(500) NOT NULL,
COD_SUCURSAL Varchar(500) NOT NULL,
FECHA Varchar(500) NOT NULL,
CANTIDAD_VENDIDA Varchar(500) NULL,
MONTO_VENDIDO Integer NULL, -- Cambie a Integer por un problema que se presentaba con los numeros negativos --
PRECIO Varchar(500) NULL,
COMISION_COMERCIAL Varchar(500) NULL
)

-- Tablas Intermedias --

CREATE TABLE [INT_DIM_PRODUCTO](
COD_PRODUCTO Varchar(15) NOT NULL,
DESC_PRODUCTO Varchar(100) NOT NULL
)

CREATE TABLE [INT_DIM_CATEGORIA](
COD_CATEGORIA Varchar(15)NOT NULL,
DESC_CATEGORIA Varchar(100)NOT NULL
)

CREATE TABLE [INT_DIM_CLIENTE] (
COD_CLIENTE Varchar(15) NOT NULL,
DESC_CLIENTE Varchar(200) NOT NULL
)

CREATE TABLE [INT_DIM_PAIS](
COD_PAIS Varchar(3) NOT NULL,
DESC_PAIS Varchar(100) NOT NULL
)

CREATE TABLE [INT_DIM_VENDEDOR](
COD_VENDEDOR Varchar(15) NOT NULL,
DESC_VENDEDOR Varchar(200) NOT NULL
)

DROP TABLE [INT_DIM_VENDEDOR]

CREATE TABLE [INT_DIM_SUCURSAL](
COD_SUCURSAL Varchar(15) NOT NULL,
DESC_SUCURSAL Varchar(100) NOT NULL
)

CREATE TABLE [INT_FACT_VENTAS] (
COD_PRODUCTO Varchar(15) NOT NULL,
COD_CATEGORIA Varchar(15) NOT NULL,
COD_CLIENTE Varchar(15) NOT NULL,
COD_PAIS Varchar(15) NOT NULL,
COD_VENDEDOR Varchar(15) NOT NULL,
COD_SUCURSAL Varchar(15)NOT NULL,
Fecha smalldatetime NOT NULL,
CANTIDAD_VENDIDA decimal(18,2) NULL,
MONTO_VENDIDO decimal(18,2) NULL,
PRECIO decimal(18,2) NULL,
COMISION_COMERCIAL decimal(18,2) NULL,
)

--Tablas de Dimensiones --

CREATE TABLE [DIM_PRODUCTO](
PRODUCTO_KEY Integer IDENTITY(1,1) NOT NULL Primary Key,
COD_PRODUCTO Varchar(15)NOT NULL,
DESC_PRODUCTO Varchar(100)NOT NULL,
FECHA_ALTA Datetime NULL,
USUARIO_ALTA Varchar(500) NULL,
FECHA_UPDATE Datetime NULL,
USUARIO_UPDATE Varchar(500) NULL -- Por que Null? --
)

CREATE TABLE [DIM_CATEGORIA](
CATEGORIA_KEY Integer IDENTITY(1,1) NOT NULL Primary Key,
COD_CATEGORIA Varchar(15) NOT NULL,
DESC_CATEGORIA Varchar(100) NOT NULL,
FECHA_ALTA Datetime NULL,
USUARIO_ALTA Varchar(500) NULL,
FECHA_UPDATE Datetime NULL,
USUARIO_UPDATE Varchar(500) NULL
)

CREATE TABLE [DIM_CLIENTE](
CLIENTE_KEY Integer IDENTITY(1,1) NOT NULL Primary Key,
COD_CLIENTE Varchar(15) NOT NULL,
DESC_CLIENTE Varchar(200) NOT NULL,
FECHA_ALTA Datetime NULL,
USUARIO_ALTA Varchar(500) NULL,
FECHA_UPDATE Datetime NULL,
USUARIO_UPDATE Varchar(500) NULL
)

CREATE TABLE [DIM_PAIS](
PAIS_KEY Integer IDENTITY(1,1) NOT NULL Primary Key,
COD_PAIS Varchar(3) NOT NULL,
DESC_PAIS Varchar(100) NOT NULL,
FECHA_ALTA Datetime NULL,
USUARIO_ALTA Varchar(500) NULL,
FECHA_UPDATE Datetime NULL,
USUARIO_UPDATE Varchar(500) NULL
)

CREATE TABLE [DIM_VENDEDOR](
VENDEDOR_KEY Integer IDENTITY(1,1) NOT NULL Primary Key,
COD_VENDEDOR Varchar(15) NOT NULL,
DESC_VENDEDOR Varchar(200) NOT NULL,
FECHA_ALTA Datetime NULL,
USUARIO_ALTA Varchar(500) NULL,
FECHA_UPDATE Datetime NULL,
USUARIO_UPDATE Varchar(500) NULL
)

CREATE TABLE [DIM_SUCURSAL] (
SUCURSAL_KEY Integer IDENTITY(1,1) NOT NULL Primary Key,
COD_SUCURSAL Varchar(15) NOT NULL,
DESC_SUCURSAL Varchar(100) NOT NULL,
FECHA_ALTA Datetime NULL,
USUARIO_ALTA Varchar(500) NULL,
FECHA_UPDATE Datetime NULL,
USUARIO_UPDATE Varchar(500) NULL
)

CREATE TABLE [DIM_TIEMPO] (
TIEMPO_KEY smalldatetime NOT NULL Primary Key,  -- (hace referencia al día)
ANIO integer NULL,
MES_NRO integer NULL,
MES_NOMBRE varchar(15) NULL,
SEMESTRE integer NULL, 
TRIMESTRE integer NULL,
SEMANA_ANIO integer NULL,
SEMANA_NRO_MES integer NULL,
DIA integer NULL,
DIA_NOMBRE varchar(20) NULL,
DIA_SEMANA_NRO integer NULL,
FECHA_ALTA Datetime NULL,
USUARIO_ALTA Varchar(500) NULL,
FECHA_UPDATE Datetime NULL,
USUARIO_UPDATE Varchar(500) NULL
)

CREATE TABLE [FACT_VENTAS] (
PRODUCTO_KEY Integer NOT NULL Foreign Key references [dbo].[DIM_PRODUCTO],
CATEGORIA_KEY Integer NOT NULL Foreign Key references [dbo].[DIM_CATEGORIA],
CLIENTE_KEY Integer NOT NULL Foreign Key references [dbo].[DIM_CLIENTE],
PAIS_KEY Integer NOT NULL Foreign Key references [dbo].[DIM_PAIS],
VENDEDOR_KEY Integer NOT NULL Foreign Key references [dbo].[DIM_VENDEDOR],
SUCURSAL_KEY Integer NOT NULL Foreign Key references [dbo].[DIM_SUCURSAL],
TIEMPO_KEY smalldatetime NOT NULL Foreign Key references [dbo].[DIM_TIEMPO],
CANTIDAD_VENDIDA decimal(18,2) NULL,
MONTO_VENDIDO decimal(18,2) NULL,
PRECIO decimal(18,2) NULL,
COMISION_COMERCIAL decimal(18,2) NULL,
FECHA_ALTA Datetime NULL,
USUARIO_ALTA Varchar(500) NULL
)


