
-- CARGO LAS TABLAS STG, CON DATOS DE LA FUENTE --

INSERT INTO [dbo].[STG_DIM_CATEGORIA] (COD_CATEGORIA, DESC_CATEGORIA)  -- INSERT INTO, DONDE QUIERO INSERTAR LOS DATOS. TABLA Y ENTRE PARENTESIS COLUMNAS DE LA STG. --
  SELECT DISTINCT -- PARA TRAER LAS COLUMNAS QUE NECESITO LLENAR, Y QUE NO SE REPITAN DICHOS DATOS)
    COD_CATEGORIA, -- COLUMNAS DE LA STG --
    DESC_CATEGORIA
  FROM [dbo].[Categoria$] -- FROM LA TABLA DE DATOS --
  WHERE COD_Categoria IS NOT NULL  -- LA CONDICION DICE QUE DONDE HAYAN DATOS, LOS TRAIGA --

INSERT INTO [dbo].[STG_DIM_CLIENTE] (COD_CLIENTE, DESC_CLIENTE)
  SELECT DISTINCT
    COD_CLIENTE,
   Desc_Cliente
FROM [dbo].[Cliente$]
  WHERE COD_Cliente is not null
  

INSERT INTO [dbo].[STG_DIM_PAIS] (COD_PAIS, DESC_PAIS)
  SELECT DISTINCT
    COD_PAIS,
    DESC_PAIS
  FROM [dbo].[Pais$]
  WHERE COD_PAIS IS NOT NULL

INSERT INTO [dbo].[STG_DIM_PRODUCTO] (COD_PRODUCTO, DESC_PRODUCTO)
  SELECT DISTINCT
    COD_PRODUCTO,
    DESC_PRODUCTO
  FROM [dbo].[Producto$]
  WHERE COD_PRODUCTO IS NOT NULL

INSERT INTO [dbo].[STG_DIM_SUCURSAL] (COD_SUCURSAL, DESC_SUCURSAL)
  SELECT DISTINCT
    COD_SUCURSAL,
    DESC_SUCURSAL
  FROM [dbo].[Sucursal$]
  WHERE COD_SUCURSAL IS NOT NULL

INSERT INTO [dbo].[STG_DIM_VENDEDOR] (COD_VENDEDOR, DESC_VENDEDOR)
  SELECT DISTINCT
    COD_VENDEDOR,
    DESC_VENDEDOR
  FROM [dbo].[Vendedor$]
  WHERE COD_VENDEDOR IS NOT NULL

INSERT INTO [dbo].[STG_FACT_VENTAS] (COD_PRODUCTO,
COD_CATEGORIA,
COD_CLIENTE,
COD_PAIS,
COD_VENDEDOR,
COD_SUCURSAL,
Fecha,
CANTIDAD_VENDIDA,
MONTO_VENDIDO,
PRECIO,
COMISION_COMERCIAL)
  SELECT
    COD_PRODUCTO,
    COD_CATEGORIA,
    COD_CLIENTE,
    COD_PAIS,
    COD_VENDEDOR,
    COD_SUCURSAL,
    Fecha,
    CANTIDAD_VENDIDA,
    MONTO_VENDIDO,
    PRECIO,
    COMISION_COMERCIAL
  FROM [dbo].[Ventas$]


  -- CARGA INICIAL INSERT INTO --

  --SETEO DE REGISTROS 0 y -1 EN TABLAS FINALES --


SET IDENTITY_INSERT DIM_CATEGORIA ON

INSERT INTO DIM_CATEGORIA (CATEGORIA_KEY, COD_CATEGORIA, DESC_CATEGORIA)
  VALUES (-1, 'S/E', 'S/E')

INSERT INTO DIM_CATEGORIA (CATEGORIA_KEY, COD_CATEGORIA, DESC_CATEGORIA)
  VALUES (0, 'N/A', 'N/A')

SET IDENTITY_INSERT DIM_CATEGORIA OFF


SET IDENTITY_INSERT DIM_CLIENTE ON

INSERT INTO DIM_CLIENTE (CLIENTE_KEY, COD_CLIENTE, DESC_CLIENTE)
  VALUES (-1, 'S/E', 'S/E', 'S/E')

INSERT INTO DIM_CLIENTE (CLIENTE_KEY, COD_CLIENTE, DESC_CLIENTE)
  VALUES (0, 'N/A', 'N/A', 'N/A')

SET IDENTITY_INSERT DIM_CLIENTE OFF



SET IDENTITY_INSERT DIM_PAIS ON

INSERT INTO DIM_PAIS (PAIS_KEY, COD_PAIS, DESC_PAIS)
  VALUES (-1, 'S/E', 'S/E')

INSERT INTO DIM_PAIS (PAIS_KEY, COD_PAIS, DESC_PAIS)
  VALUES (0, 'N/A', 'N/A')

SET IDENTITY_INSERT DIM_PAIS OFF



SET IDENTITY_INSERT DIM_PRODUCTO ON

INSERT INTO DIM_PRODUCTO (PRODUCTO_KEY, COD_PRODUCTO, DESC_PRODUCTO)
  VALUES (-1, 'S/E', 'S/E')

INSERT INTO DIM_PRODUCTO (PRODUCTO_KEY, COD_PRODUCTO, DESC_PRODUCTO)
  VALUES (0, 'N/A', 'N/A')

SET IDENTITY_INSERT DIM_PRODUCTO OFF



SET IDENTITY_INSERT DIM_SUCURSAL ON

INSERT INTO DIM_SUCURSAL (SUCURSAL_KEY, COD_SUCURSAL, DESC_SUCURSAL)
  VALUES (-1, 'S/E', 'S/E')

INSERT INTO DIM_SUCURSAL (SUCURSAL_KEY, COD_SUCURSAL, DESC_SUCURSAL)
  VALUES (0, 'N/A', 'N/A')

SET IDENTITY_INSERT DIM_SUCURSAL OFF



SET IDENTITY_INSERT DIM_VENDEDOR ON

INSERT INTO DIM_VENDEDOR (VENDEDOR_KEY, COD_VENDEDOR, DESC_VENDEDOR)
  VALUES (-1, 'S/E', 'S/E', 'S/E')

INSERT INTO DIM_VENDEDOR (VENDEDOR_KEY, COD_VENDEDOR, DESC_VENDEDOR)
  VALUES (0, 'N/A', 'N/A', 'N/A')

SET IDENTITY_INSERT DIM_VENDEDOR OFF